#!/bin/bash

gcc -o nosuchcon_2013_whitebox_allenc_generator ../target/nosuchcon_2013_whitebox_allenc_generator.c
gcc -o nosuchcon_2013_whitebox_allenc ../target/nosuchcon_2013_whitebox_allenc.c
./nosuchcon_2013_whitebox_allenc_generator

gcc -o nosuchcon_2013_whitebox_generator_noenc_nokey nosuchcon_2013_whitebox_generator_noenc_nokey.c
./nosuchcon_2013_whitebox_generator_noenc_nokey
gcc -o nosuchcon_2013_whitebox_nsc_break nosuchcon_2013_whitebox_nsc_break.c
./nosuchcon_2013_whitebox_nsc_break
